
$wolfPack = @'
MMMMMMMMMMMMMMMMXc  .;d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d;.  cXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWd.     .;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o;.     .dWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMk. .;.     .,oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,.     .;. .kMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMX: .kWKc.      .:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.      .cKWk. :XMMMMMMMMMMMMMM
MMMMMMMMMMMMMMk. oWMMNx.        ;kXXKNMMMMMMMMMMMMMMMMMMMMMMMMNKXNx;.       .xNMMWo .kMMMMMMMMMMMMMM
MMMMMMMMMMMMMWo '0MMMMW0;         ,l;;oONMMMMMMMMMMMMMMMMMMNOo;;l,         ;0WMMMM0' oWMMMMMMMMMMMMM
MMMMMMMMMMMMMX: ;XMMMMMMXl.            .,lONMMMMMMMMMMMMNOl,.            .lXMMMMMMX; :NMMMMMMMMMMMMM
MMMMMMMMMMMMMX; cNMMMMMMWKl.               'lkXWMMMMWXkl'               .lKWMMMMMMNc ;XMMMMMMMMMMMMM
MMMMMMMMMMMMMX; cNMMMMMMWXko:'.               .ck00kc'               .':okXWMMMMMMNc ;XMMMMMMMMMMMMM
MMMMMMMMMMMMMX; :NMMMMMMMMMMMNX0kdl:,..          ..          ..,:ldk0XNWMMMMMMMMMMN: ;XMMMMMMMMMMMMM
MMMMMMMMMMMMMNc ;KMMMMMMMMMMMMMMMMMMWNK0kdoc:,...  ...,:codk0KNWMMMMMMMMMMMMMMMMMMK, cNMMMMMMMMMMMMM
MMMMMMMMMMMMMWl .OMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OO0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMk. lWMMMMMMMMMMMMM
MMMMMMMMMMMMMMx. lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl..xWMMMMMMMMMMMMM
MMMMMMMMMMMMMMO. .kWMMMMMWNX0O0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0O0XWMMMMMMWO' 'OMMMMMMMMMMMMMM
MMMMMMMMMMMMMMX;  'OWMMN0o:'..lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl..':o0WMMWO,  ;XMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWo   .cxxc;co:cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc:oc;cxxc.   oWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM0'   .;okXWNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKNWXko;.   '0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMX:  .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd.  :XMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW0c.   .lXMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMXl.   .c0WMMMMMMMMMMMMM
MMMMMMMMMMMWKl.    .cONMMMMMMMMMWWNXKkxkXWMMMMMMMMMMMMMMMMWXkxkKXNWWMMMMMMMMMNOc.    .lKMMMMMMMMMMMM
MMMMMMMMMMNx'    .c0WMMMMMMWKkoc;,'','. 'l0WMMMMMMMMMMMMW0l' .','',;cokKWMMMMMMW0c.    'xNMMMMMMMMMM
MMMMMMMMMKc.    ,OWMMMMMN0o,.       .,,.  .c0WMMMMMMMMW0c.  .,;.       .,o0WMMMMMWO,    .cKMMMMMMMMM
MMMMMMMW0;    .lXMMMMMNk;.       .,cdOKOc.  .dNMMMMMMNd.  .cOKOdl,.       .;kNMMMMMXl.    ;0MMMMMMMM
MMMMMMWO'    .xWMMMMW0:.        .,cd0NMMWk'   lXMMMMXl   'kNMWN0dc,.        .:0WMMMMWx.    'OWMMMMMM
MMMMMWO,    ;0WMMMMWx.           'l:.,okOOd'  .dWMMWd.  'xOOko,.:l'           .xWMMMMW0;    ,0MMMMMM
MMMMMK;    cKMMMMMWd.    'kx'  ':;okdl'   ..   ;XMMX:  ...   .lxko;:'  'xk,    .dWMMMMMKc    ;KMMMMM
MMMMXc   .oNMMMMMWk.  .' .cKKl..lkocc:.   .    ,KMMK;    .   .:ccokl..lKKc. '.  .kWMMMMMNo.   cXMMMM
MMMWd.  .xNKOKMMMK;  ;0k.  :XW0l;oKNX0Ox;cOx;  ;XMMX;  ;xOc;dO0XNKo;l0WX:  .k0;  ;KMMMXOXNx.  .dWMMM
MMM0,  .od:.'OMMWd. :KMK,  .dX0kdldKWMMMK0WMXc.lNMMNl.cXMW0KMMMWKdldk0Xd.  ,KMK: .dWMMO'.:do.  ,0MMM
MMWo   ..   ,KMMNc ,0MMWo   .,:lc,';kNMMMMMMMk;kMMMMk;kMMMMMMMNk;',cl:,.   oWMM0, cNMMK,   ..   oWMM
MM0'    .;. cNMMX;.dWMMMK,   ,KMWXd..cXMMMMMMkdXMMMMXdkMMMMMMXc..dXWMK;   ,KMMMWd.;XMMNc .;.    '0MM
MWd.  .cKk. lWMMX:'0MMMMWk. .dWMMMWk. lNMMMMN0KMMMMMMK0NMMMMNl .kWMMMWx. .OWMMMM0':XMMWl .kKc.  .dWM
MX:  'kWWd. cKWMWo:KMMMMMWk'.OMMMMMNc .OMMMMWWMMMMMMMMWWMMMMO. cNMMMMMO.'kWMMMMMK:oWMWKc .xMWk'  :XM
M0' cKMMWd  .'dNMKxKMMMMMMW0oOMMMMMWx. oWMMMMMMMMMMMMMMMMMMWo .xMMMMMMOo0WMMMMMMKxKMNd'.  dWMWKc '0M
Mx'oNMMMWd    .oNWNWMMMMMMMMNNWMMMMM0' :XWMMMMMMMMMMMMMMMMWX: '0MMMMMMNNMMMMMMMMWNMNo.   .dWMMMNo'xM
WkkNMMMMWd.    .lXMMMMMMMMMMMMMMMMMMX: ,ldXMMMMMMMMMMMMMMXdo, :XMMMMMMMMMMMMMMMMMMXl.    .dWMMMMNkkW
WWWMMMMMMd.  .   ;0WMMMMMMMMMMMMMMMMWo ...:XMMMMMMMMMMMMX:... oWMMMMMMMMMMMMMMMMWO;  ..  .dWMMMMMWWM
MMMMMMMMMk. .dl   .oXMMMMMWWMMMMMMMMMO.   .dKOxxkkkkxxOKd.   .OMMMMMMMMMWWMMMMMXo.  .ox. .kMMMMMMMMM
MMMMMMMMMO. lNXl    ,kNMMWOo0WMMMMMMMX;  .lc.          .ll.  ;XMMMMMMMW0oOMMMNk;.  .lXNl .OMMMMMMMMM
MMMMMMMMMK;.OMMNo.   .;xNWo .xNMMMMMMWo  'l'            'l'  oWMMMMMMNx. oWNk;.   .oNMMO.;KMMMMMMMMM
MMMMMMMMMNl:XMMMWk'     ,o;  .lXMMMMMMO. 'd;  ..    ..  ;d' .OMMMMMMXl.  ;o,     'kWMMMX:lNMMMMMMMMM
MMMMMMMMMMOkNMMMMWKl.          ,OWMMMMNc .x0l:kd.  .dk:c0x. cNMMMMWO,          .lKMMMMMNkOMMMMMMMMMM
MMMMMMMMMMNNWMMMMMMW0c.         .oXMMMW0, :XXl,.    .,lXK; ,OWMMMNo.         .c0WMMMMMMWNNMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0c.    ;:.  ;OWW0O0c.;kOdc'..':dOk;.:0O0WWO;  .:;    .c0WMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0o'  .dx'  .l0o'xXO:,:okkkkkko:':kXx'o0l.  'xd.  'o0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMXk:.,kKl.  .. .oNWKd:,'..',:o0WNo. ..  .lKk'.:kXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxdOXO;      lXMMWNK00KXWMMXl.    .;OXOoxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWXd.     :KMMMMMMMMMMK:.    .dXWNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.    ,OWMMMMMMWO;.   .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'    .dNMMMMNx'.   'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.    :0NN0c.   .lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;    .;;.    ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.        .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.    .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,..,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    
'@

Start-Sleep -Seconds 152

Write-Output $wolfPack
